const data = {
  activities: [
    {
      title: "副本",
      titleBackgroundColor: "#f5222d",
      inProgressBackgroundColor: "#ffccc7",
      icon: "/static/imgs/instance.png",
      events: [
        {
          name: "悉拉玛卡的末日",
          icon: "/static/imgs/fall_of_hiram.png",
          times: [
            {
              day: 7,
              hours: 2,
              minutes: 0,
              seconds: 0,
              last: 120,
            },
            {
              day: 7,
              hours: 10,
              minutes: 0,
              seconds: 0,
              last: 360,
            },
          ],
        },
        {
          name: "黄金平原战争",
          icon: "/static/imgs/gold_plain.png",
          times: [
            {
              day: 7,
              hours: 6,
              minutes: 30,
              seconds: 0,
              last: 45,
            },
            {
              day: 7,
              hours: 12,
              minutes: 30,
              seconds: 0,
              last: 45,
            },
            {
              day: 7,
              hours: 17,
              minutes: 30,
              seconds: 0,
              last: 30,
            },
          ],
        },
        {
          name: "红龙副本",
          icon: "/static/imgs/dragon_red.png",
          times: [
            {
              day: 1,
              hours: 7,
              minutes: 15,
              seconds: 0,
              last: 45,
            },
            {
              day: 1,
              hours: 13,
              minutes: 15,
              seconds: 0,
              last: 45,
            },
            {
              day: 0,
              hours: 18,
              minutes: 0,
              seconds: 0,
              last: 30,
            },
            {
              day: 3,
              hours: 7,
              minutes: 15,
              seconds: 0,
              last: 45,
            },
            {
              day: 3,
              hours: 13,
              minutes: 15,
              seconds: 0,
              last: 45,
            },
            {
              day: 2,
              hours: 18,
              minutes: 0,
              seconds: 0,
              last: 30,
            },
            {
              day: 5,
              hours: 7,
              minutes: 15,
              seconds: 0,
              last: 45,
            },
            {
              day: 5,
              hours: 13,
              minutes: 15,
              seconds: 0,
              last: 45,
            },
            {
              day: 4,
              hours: 18,
              minutes: 0,
              seconds: 0,
              last: 30,
            },
            {
              day: 0,
              hours: 7,
              minutes: 15,
              seconds: 0,
              last: 45,
            },
            {
              day: 0,
              hours: 13,
              minutes: 15,
              seconds: 0,
              last: 45,
            },
            {
              day: 6,
              hours: 18,
              minutes: 0,
              seconds: 0,
              last: 30,
            },
          ],
        },
      ],
    },
    {
      title: "日常",
      titleBackgroundColor: "#a0d911",
      inProgressBackgroundColor: "#f4ffb8",
      icon: "/static/imgs/daily.png",

      events: [
        {
          name: "征兆之痕",
          icon: "/static/imgs/crimson_rift.png",
          times: [
            {
              day: 7,
              hours: 0,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 4,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 8,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 12,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 16,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 20,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
          ],
        },
        {
          name: "噩梦之痕",
          icon: "/static/imgs/grimghast_rift.png",
          times: [
            {
              day: 7,
              hours: 2,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 6,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 10,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 14,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 18,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 22,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
          ],
        },
      ],
    },
    {
      title: "世界boss",
      titleBackgroundColor: "#722ed1",
      inProgressBackgroundColor: "#efdbff",
      icon: "/static/imgs/boss.png",
      events: [
        {
          name: "美杜莎-梅娜-格兰",
          icon: "/static/imgs/boss_monster.png",
          times: [
            {
              day: 7,
              hours: 3,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 7,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 11,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 15,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 19,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
            {
              day: 7,
              hours: 23,
              minutes: 20,
              seconds: 0,
              last: 10,
            },
          ],
        },
        {
          name: "德菲娜幽灵船",
          icon: "/static/imgs/delphinad_ghost_ships.png",
          times: [
            {
              day: 7,
              hours: 13,
              minutes: 45,
              seconds: 0,
              last: 10,
            },
          ],
        },
        {
          name: "利维坦",
          icon: "/static/imgs/leviathan.png",
          times: [
            {
              day: 2,
              hours: 13,
              minutes: 30,
              seconds: 0,
              last: 10,
            },
            {
              day: 4,
              hours: 13,
              minutes: 30,
              seconds: 0,
              last: 10,
            },
            {
              day: 6,
              hours: 13,
              minutes: 30,
              seconds: 0,
              last: 10,
            },
          ],
        },
        {
          name: "克拉肯",
          icon: "/static/imgs/kraken.png",
          times: [
            {
              day: 2,
              hours: 13,
              minutes: 35,
              seconds: 0,
              last: 10,
            },
            {
              day: 4,
              hours: 13,
              minutes: 35,
              seconds: 0,
              last: 10,
            },
            {
              day: 6,
              hours: 13,
              minutes: 35,
              seconds: 0,
              last: 10,
            },
          ],
        },
      ],
    },
  ],
  continents: [
    {
      name: "诺伊大陆",
      areas: [
        {
          name: "双管丘陵",
          warArea: false,
          packs: [
            {
              origin: "索子里德半岛",
              level: 1,
              normal: 15.6296,
              glida: 37.3298,
              local: 17.1922,
              fertilizer: 17.9741,
              salve: 25.2607,
              cheese: 25.3885,
              honey: 25.3371,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 1
            },
            {
              origin: "双管丘陵",
              level: 1,
              normal: 0,
              glida: 0,
              local: 0,
              fertilizer: 0,
              salve: 0,
              cheese: 0,
              honey: 0,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 2
            },
            {
              origin: "十字星平原",
              level: 1,
              normal: 12.7855,
              glida: 38.4508,
              local: 15.4658,
              fertilizer: 16.169,
              salve: 26.4637,
              cheese: 26.6773,
              honey: 26.6508,
              bluesalt: 82.5662,
              special: 26.2604,
              antiquities: 0,
              order: 3
            },
            {
              origin: "黎利尔丘陵",
              level: 2,
              normal: 15.9438,
              glida: 39.4333,
              local: 16.298,
              fertilizer: 17.0389,
              salve: 23.4337,
              cheese: 23.4337,
              honey: 23.4809,
              bluesalt: 85.9138,
              special: 0,
              antiquities: 0,
              order: 4
            },
            {
              origin: "碎石平原",
              level: 2,
              normal: 16.0054,
              glida: 37.3680,
              local: 17.6058,
              fertilizer: 18.4064,
              salve: 23.0398,
              cheese: 22.8782,
              honey: 22.8549,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 5
            },
            {
              origin: "马瑞诺普",
              level: 2,
              normal: 10.9539,
              glida: 35.1278,
              local: 12.0492,
              fertilizer: 12.5969,
              salve: 21.4539,
              cheese: 21.3895,
              honey: 21.4539,
              bluesalt: 83.8429,
              special: 0,
              antiquities: 0,
              order: 6
            },
            {
              origin: "格威尔森林",
              level: 3,
              normal: 15.4681,
              glida: 38.3366,
              local: 16.1088,
              fertilizer: 16.8407,
              salve: 24.3383,
              cheese: 24.3628,
              honey: 24.3383,
              bluesalt: 91.7079,
              special: 0,
              antiquities: 0,
              order: 7
            },
            {
              origin: "青铜岩石山",
              level: 3,
              normal: 15.0386,
              glida: 37.4938,
              local: 15.4102,
              fertilizer: 16.1107,
              salve: 24.4853,
              cheese: 21.6424,
              honey: 24.436,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 8
            },
            {
              origin: "太初之地",
              level: 3,
              normal: 14.6178,
              glida: 35.6083,
              local: 15.1734,
              fertilizer: 15.8631,
              salve: 22.4588,
              cheese: 16.7913,
              honey: 22.3236,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 9
            },
            {
              origin: "白雪森林",
              level: 3,
              normal: 13.5804,
              glida: 33.7224,
              local: 14.9386,
              fertilizer: 15.6173,
              salve: 22.4138,
              cheese: 22.5266,
              honey: 22.4362,
              bluesalt: 95.9136,
              special: 0,
              antiquities: 10.9919,
              order: 10
            },
            {
              origin: "埋骨之地",
              level: 3,
              normal: 18.0735,
              glida: 37.1043,
              local: 19.8812,
              fertilizer: 20.7851,
              salve: 21.9549,
              cheese: 21.9549,
              honey: 28.2609,
              bluesalt: 0,
              special: 38.5782,
              antiquities: 0,
              order: 11
            },
            {
              origin: "黄金平原",
              level: 4,
              normal: 14.8365,
              glida: 32.0522,
              local: 17.9863,
              fertilizer: 18.8038,
              salve: 24.9045,
              cheese: 24.9546,
              honey: 24.9799,
              bluesalt: 0,
              special: 27.7888,
              antiquities: 0,
              order: 12
            },
            {
              origin: "地狱沼泽",
              level: 4,
              normal: 17.082,
              glida: 35.6473,
              local: 18.7903,
              fertilizer: 19.6444,
              salve: 26.8205,
              cheese: 26.6587,
              honey: 26.8205,
              bluesalt: 0,
              special: 34.7698,
              antiquities: 0,
              order: 13
            },
            {
              origin: "珊瑚海岸",
              level: 4,
              normal: 16.6336,
              glida: 34.3779,
              local: 19.408,
              fertilizer: 20.29,
              salve: 24.8046,
              cheese: 24.7548,
              honey: 24.8046,
              bluesalt: 0,
              special: 28.3361,
              antiquities: 0,
              order: 14
            },
            {
              origin: "西风脊",
              level: 4,
              normal: 18.7318,
              glida: 37.6534,
              local: 20.6049,
              fertilizer: 21.5413,
              salve: 27.7226,
              cheese: 24.919,
              honey: 27.7783,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 15
            },
          ],
        },
        {
          name: "索子里德半岛",
          warArea: false,
          packs: [
            {
              origin: "索子里德半岛",
              level: 1,
              normal: 0,
              glida: 0,
              local: 0,
              fertilizer: 0,
              salve: 0,
              cheese: 0,
              honey: 0,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 1
            },
            {
              origin: "双管丘陵",
              level: 1,
              normal: 16.2092,
              glida: 38.8584,
              local: 17.8303,
              fertilizer: 18.6404,
              salve: 25.4645,
              cheese: 25.2866,
              honey: 25.4392,
              bluesalt: 0,
              special: 0,
              antiquities: 10.4802,
              order: 2
            },
            {
              origin: "十字星平原",
              level: 1,
              normal: 13.8333,
              glida: 38.1025,
              local: 16.6186,
              fertilizer: 17.3741,
              salve: 26.6505,
              cheese: 26.5439,
              honey: 26.4906,
              bluesalt: 83.9304,
              special: 30.3862,
              antiquities: 0,
              order: 3
            },
            {
              origin: "黎利尔丘陵",
              level: 2,
              normal: 11.818,
              glida: 33.3627,
              local: 13.0002,
              fertilizer: 13.5909,
              salve: 21.2819,
              cheese: 21.4108,
              honey: 21.4108,
              bluesalt: 83.4384,
              special: 0,
              antiquities: 0,
              order: 4
            },
            {
              origin: "碎石平原",
              level: 2,
              normal: 11.8618,
              glida: 34.0620,
              local: 13.0479,
              fertilizer: 13.6408,
              salve: 22.3911,
              cheese: 22.3235,
              honey: 22.4815,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 5
            },
            {
              origin: "马瑞诺普",
              level: 2,
              normal: 14.8736,
              glida: 35.3400,
              local: 16.3611,
              fertilizer: 17.105,
              salve: 22.3462,
              cheese: 22.3237,
              honey: 22.4138,
              bluesalt: 85.8871,
              special: 0,
              antiquities: 0,
              order: 6
            },
            {
              origin: "格威尔森林",
              level: 3,
              normal: 15.0998,
              glida: 33.3871,
              local: 16.61,
              fertilizer: 17.3649,
              salve: 23.3649,
              cheese: 23.3883,
              honey: 23.3176,
              bluesalt: 86.6842,
              special: 0,
              antiquities: 0,
              order: 7
            },
            {
              origin: "青铜岩石山",
              level: 3,
              normal: 16.0137,
              glida: 36.3943,
              local: 17.3889,
              fertilizer: 18.1794,
              salve: 26.3646,
              cheese: 26.3115,
              honey: 26.2056,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 8
            },
            {
              origin: "太初之地",
              level: 3,
              normal: 15.621,
              glida: 34.5888,
              local: 17.1834,
              fertilizer: 17.9646,
              salve: 22.3909,
              cheese: 22.3459,
              honey: 22.5041,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 9
            },
            {
              origin: "白雪森林",
              level: 3,
              normal: 15.6879,
              glida: 34.7654,
              local: 17.2565,
              fertilizer: 18.0409,
              salve: 21.353,
              cheese: 21.3744,
              honey: 21.4392,
              bluesalt: 89.1636,
              special: 0,
              antiquities: 13.1996,
              order: 10
            },
            {
              origin: "埋骨之地",
              level: 3,
              normal: 19.8123,
              glida: 37.7534,
              local: 21.7935,
              fertilizer: 22.7842,
              salve: 32.0291,
              cheese: 32.2561,
              honey: 32.2236,
              bluesalt: 0,
              special: 50.1488,
              antiquities: 0,
              order: 11
            },
            {
              origin: "黄金平原",
              level: 4,
              normal: 16.7304,
              glida: 33.8001,
              local: 18.4031,
              fertilizer: 19.2399,
              salve: 29.6044,
              cheese: 29.694,
              honey: 29.6644,
              bluesalt: 0,
              special: 42.0862,
              antiquities: 0,
              order: 12
            },
            {
              origin: "地狱沼泽",
              level: 4,
              normal: 20.1292,
              glida: 38.8311,
              local: 21.5868,
              fertilizer: 22.568,
              salve: 30.6209,
              cheese: 30.5598,
              honey: 30.5598,
              bluesalt: 0,
              special: 59.6674,
              antiquities: 0,
              order: 13
            },
            {
              origin: "珊瑚海岸",
              level: 4,
              normal: 17.7294,
              glida: 34.8153,
              local: 19.5026,
              fertilizer: 20.3891,
              salve: 28.8226,
              cheese: 28.6785,
              honey: 28.7361,
              bluesalt: 0,
              special: 38.4007,
              antiquities: 0,
              order: 14
            },
            {
              origin: "西风脊",
              level: 4,
              normal: 20.6341,
              glida: 38.8080,
              local: 22.6979,
              fertilizer: 23.7294,
              salve: 35.2275,
              cheese: 35.3347,
              honey: 35.5122,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 15
            },
          ],
        },
        {
          name: "十字星平原",
          warArea: true,
          packs: [
            {
              origin: "索子里德半岛",
              level: 1,
              normal: 13.8334,
              glida: 42.3359,
              local: 16.6188,
              fertilizer: 17.3741,
              salve: 30.133,
              cheese: 30.0421,
              honey: 30.1635,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 1
            },
            {
              origin: "双管丘陵",
              level: 1,
              normal: 12.7855,
              glida: 40.9050,
              local: 15.466,
              fertilizer: 16.169,
              salve: 27.7502,
              cheese: 27.7225,
              honey: 27.7225,
              bluesalt: 0,
              special: 0,
              antiquities: 9.74,
              order: 2
            },
            {
              origin: "十字星平原",
              level: 1,
              normal: 0,
              glida: 0,
              local: 0,
              fertilizer: 0,
              salve: 0,
              cheese: 0,
              honey: 0,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 3
            },
            {
              origin: "黎利尔丘陵",
              level: 2,
              normal: 17.598,
              glida: 43.6359,
              local: 19.3578,
              fertilizer: 20.238,
              salve: 25.6674,
              cheese: 25.6928,
              honey: 25.5384,
              bluesalt: 92.3472,
              special: 0,
              antiquities: 0,
              order: 4
            },
            {
              origin: "碎石平原",
              level: 2,
              normal: 16.8696,
              glida: 41.4385,
              local: 18.5565,
              fertilizer: 19.3998,
              salve: 24.5484,
              cheese: 24.5733,
              honey: 24.672,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 5
            },
            {
              origin: "马瑞诺普",
              level: 2,
              normal: 15.4664,
              glida: 39.0549,
              local: 18.2531,
              fertilizer: 19.0829,
              salve: 23.5047,
              cheese: 23.5282,
              honey: 23.5047,
              bluesalt: 90.1674,
              special: 0,
              antiquities: 0,
              order: 6
            },
            {
              origin: "格威尔森林",
              level: 3,
              normal: 16.6356,
              glida: 42.3221,
              local: 18.2992,
              fertilizer: 19.1308,
              salve: 24.3871,
              cheese: 24.3139,
              honey: 24.2893,
              bluesalt: 98.4466,
              special: 0,
              antiquities: 0,
              order: 7
            },
            {
              origin: "青铜岩石山",
              level: 3,
              normal: 16.4491,
              glida: 41.426,
              local: 18.0938,
              fertilizer: 18.9164,
              salve: 28.346,
              cheese: 29.0369,
              honey: 28.1757,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 8
            },
            {
              origin: "太初之地",
              level: 3,
              normal: 15.931,
              glida: 39.4195,
              local: 17.5243,
              fertilizer: 18.3211,
              salve: 26.365,
              cheese: 23.2414,
              honey: 26.3383,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 9
            },
            {
              origin: "白雪森林",
              level: 3,
              normal: 15.2375,
              glida: 37.4135,
              local: 16.761,
              fertilizer: 17.5231,
              salve: 23.2943,
              cheese: 23.3881,
              honey: 23.3177,
              bluesalt: 92.3471,
              special: 0,
              antiquities: 12.7275,
              order: 10
            },
            {
              origin: "埋骨之地",
              level: 3,
              normal: 21.1536,
              glida: 41.0116,
              local: 22.115,
              fertilizer: 28.1757,
              salve: 28.5207,
              cheese: 28.5207,
              honey: 32.2235,
              bluesalt: 0,
              special: 45.7717,
              antiquities: 0,
              order: 11
            },
            {
              origin: "黄金平原",
              level: 4,
              normal: 16.3493,
              glida: 36.7318,
              local: 18.5394,
              fertilizer: 19.3822,
              salve: 24.9299,
              cheese: 24.8795,
              honey: 24.8546,
              bluesalt: 0,
              special: 29.096,
              antiquities: 0,
              order: 12
            },
            {
              origin: "地狱沼泽",
              level: 4,
              normal: 18.2482,
              glida: 39.4317,
              local: 20.0729,
              fertilizer: 20.9855,
              salve: 28.7071,
              cheese: 28.8227,
              honey: 28.8227,
              bluesalt: 0,
              special: 41.9634,
              antiquities: 0,
              order: 13
            },
            {
              origin: "珊瑚海岸",
              level: 4,
              normal: 18.6815,
              glida: 38.0819,
              local: 22.2159,
              fertilizer: 23.2255,
              salve: 24.9046,
              cheese: 24.9546,
              honey: 24.8298,
              bluesalt: 0,
              special: 35.5297,
              antiquities: 0,
              order: 14
            },
            {
              origin: "西风脊",
              level: 4,
              normal: 19.7355,
              glida: 41.5662,
              local: 21.709,
              fertilizer: 22.6962,
              salve: 32.6332,
              cheese: 31.3139,
              honey: 32.4695,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 15
            },
          ],
        },
      ],
    },
    {
      name: "哈里兰大陆",
      areas: [
        {
          name: "黎明半岛",
          warArea: false,
          packs: [
            {
              origin: "黎明半岛",
              level: 1,
              normal: 0,
              glida: 0,
              local: 0,
              fertilizer: 0,
              salve: 0,
              cheese: 0,
              honey: 0,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 1
            },
            {
              origin: "咏唱之地",
              level: 1,
              normal: 18.1288,
              glida: 39.6737,
              local: 19.9416,
              fertilizer: 20.8480,
              salve: 30.1635,
              cheese: 30.1635,
              honey: 30.3152,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 2
            },
            {
              origin: "莫哈特比",
              level: 2,
              normal: 10.6712,
              glida: 33.4958,
              local: 11.7381,
              fertilizer: 12.2718,
              salve: 23.4572,
              cheese: 23.5757,
              honey: 23.5283,
              bluesalt: 83.6786,
              special: 0,
              antiquities: 0,
              order: 3
            },
            {
              origin: "猎鹰高原",
              level: 2,
              normal: 16.9933,
              glida: 37.6185,
              local: 18.6928,
              fertilizer: 19.5423,
              salve: 20.4441,
              cheese: 20.4441,
              honey: 20.9560,
              bluesalt: 88.6152,
              special: 0,
              antiquities: 0,
              order: 4
            },
            {
              origin: "虎脊山脉",
              level: 2,
              normal: 15.1491,
              glida: 35.4732,
              local: 16.6640,
              fertilizer: 17.4216,
              salve: 24.6719,
              cheese: 24.5235,
              honey: 24.5235,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 5
            },
            {
              origin: "彩虹荒野",
              level: 3,
              normal: 15.1471,
              glida: 33.5207,
              local: 16.6619,
              fertilizer: 17.4192,
              salve: 25.3374,
              cheese: 25.4137,
              honey: 25.2352,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 6
            },
            {
              origin: "烈日峡谷",
              level: 3,
              normal: 15.8139,
              glida: 35.0996,
              local: 17.3952,
              fertilizer: 18.1858,
              salve: 27.3413,
              cheese: 27.2315,
              honey: 27.3413,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 7
            },
            {
              origin: "古代森林",
              level: 3,
              normal: 15.9025,
              glida: 35.3263,
              local: 17.4930,
              fertilizer: 18.2880,
              salve: 26.3912,
              cheese: 26.2325,
              honey: 26.3383,
              bluesalt: 88.4798,
              special: 0,
              antiquities: 0,
              order: 8
            },
            {
              origin: "伊尼斯泰尔",
              level: 3,
              normal: 16.3098,
              glida: 33.7951,
              local: 19.0729,
              fertilizer: 19.9403,
              salve: 24.3136,
              cheese: 24.2894,
              honey: 24.3875,
              bluesalt: 87.8914,
              special: 37.6695,
              antiquities: 0,
              order: 9
            },
            {
              origin: "草原之脉",
              level: 4,
              normal: 18.2484,
              glida: 35.4597,
              local: 20.0728,
              fertilizer: 20.9855,
              salve: 23.2472,
              cheese: 23.2472,
              honey: 23.8390,
              bluesalt: 0,
              special: 41.8132,
              antiquities: 0,
              order: 10
            },
            {
              origin: "哈里洛废墟",
              level: 4,
              normal: 19.3115,
              glida: 36.8178,
              local: 21.2426,
              fertilizer: 22.2082,
              salve: 29.5450,
              cheese: 29.6642,
              honey: 29.5748,
              bluesalt: 92.7937,
              special: 49.0068,
              antiquities: 14.1536,
              order: 11
            },
            {
              //current
              origin: "棋盘石林",
              level: 4,
              normal: 19.3118,
              glida: 36.8009,
              local: 21.2424,
              fertilizer: 22.2084,
              salve: 25.8139,
              cheese: 25.1698,
              honey: 25.1698,
              bluesalt: 0,
              special: 48.9157,
              antiquities: 0,
              order: 12
            },
            {
              origin: "翡翠谷",
              level: 4,
              normal: 20.8981,
              glida: 39.2787,
              local: 22.9884,
              fertilizer: 24.0328,
              salve: 37.1319,
              cheese: 37.3193,
              honey: 37.2822,
              bluesalt: 0,
              special: 64.038,
              antiquities: 15.8482,
              order: 13
            },
            {
              origin: "洛卡山脉",
              level: 4,
              normal: 19.6760,
              glida: 37.3900,
              local: 21.6441,
              fertilizer: 22.6279,
              salve: 37.3773,
              cheese: 37.3773,
              honey: 38.3509,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 14
            },
          ],
        },
        {
          name: "咏唱之地",
          warArea: false,
          packs: [
            {
              origin: "黎明半岛",
              level: 1,
              normal: 18.1288,
              glida: 40.5755,
              local: 19.9416,
              fertilizer: 20.8480,
              salve: 28.8696,
              cheese: 29.0443,
              honey: 28.8405,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 1
            },
            {
              origin: "咏唱之地",
              level: 1,
              normal: 0,
              glida: 0,
              local: 0,
              fertilizer: 0,
              salve: 0,
              cheese: 0,
              honey: 0,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 2
            },
            {
              origin: "莫哈特比",
              level: 2,
              normal: 10.6712,
              glida: 34.5630,
              local: 11.7383,
              fertilizer: 12.2715,
              salve: 23.4575,
              cheese: 23.4103,
              honey: 23.4575,
              bluesalt: 83.6216,
              special: 0,
              antiquities: 0,
              order: 3
            },
            {
              origin: "猎鹰高原",
              level: 2,
              normal: 16.9933,
              glida: 38.8230,
              local: 18.6926,
              fertilizer: 19.5423,
              salve: 24.5979,
              cheese: 24.5485,
              honey: 24.5485,
              bluesalt: 88.5583,
              special: 0,
              antiquities: 0,
              order: 4
            },
            {
              origin: "虎脊山脉",
              level: 2,
              normal: 15.1491,
              glida: 36.6066,
              local: 16.6640,
              fertilizer: 17.4215,
              salve: 24.4743,
              cheese: 24.6718,
              honey: 24.6473,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 5
            },
            {
              origin: "彩虹荒野",
              level: 3,
              normal: 15.1474,
              glida: 34.5933,
              local: 16.6619,
              fertilizer: 17.4194,
              salve: 23.3413,
              cheese: 23.4116,
              honey: 24.3625,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 6
            },
            {
              origin: "烈日峡谷",
              level: 3,
              normal: 15.8139,
              glida: 36.2247,
              local: 17.3950,
              fertilizer: 18.1861,
              salve: 24.3872,
              cheese: 24.4364,
              honey: 25.3628,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 7
            },
            {
              origin: "古代森林",
              level: 3,
              normal: 10.6275,
              glida: 31.9335,
              local: 11.8311,
              fertilizer: 12.3688,
              salve: 20.5471,
              cheese: 20.5263,
              honey: 20.4441,
              bluesalt: 86.7419,
              special: 0,
              antiquities: 0,
              order: 8
            },
            {
              origin: "伊尼斯泰尔",
              level: 3,
              normal: 16.5972,
              glida: 34.3706,
              local: 19.3895,
              fertilizer: 20.2708,
              salve: 24.3626,
              cheese: 24.4363,
              honey: 24.4853,
              bluesalt: 87.1917,
              special: 34.1068,
              antiquities: 0,
              order: 9
            },
            {
              origin: "草原之脉",
              level: 4,
              normal: 18.2481,
              glida: 36.5979,
              local: 20.0728,
              fertilizer: 20.9852,
              salve: 24.7544,
              cheese: 24.7544,
              honey: 24.9048,
              bluesalt: 0,
              special: 41.5857,
              antiquities: 0,
              order: 10
            },
            {
              origin: "哈里洛废墟",
              level: 4,
              normal: 19.2494,
              glida: 38.0014,
              local: 21.1740,
              fertilizer: 22.1365,
              salve: 27.6108,
              cheese: 27.6387,
              honey: 27.6108,
              bluesalt: 92.7366,
              special: 48.7792,
              antiquities: 14.0869,
              order: 11
            },
            {
              origin: "棋盘石林",
              level: 4,
              normal: 16.0288,
              glida: 33.5448,
              local: 18.7422,
              fertilizer: 19.5941,
              salve: 22.9197,
              cheese: 22.8503,
              honey: 23.0350,
              bluesalt: 0,
              special: 25.9383,
              antiquities: 0,
              order: 12
            },
            {
              origin: "翡翠谷",
              level: 4,
              normal: 20.8458,
              glida: 40.4921,
              local: 22.9309,
              fertilizer: 23.9730,
              salve: 35.2275,
              cheese: 35.3700,
              honey: 35.5124,
              bluesalt: 0,
              special: 61.5466,
              antiquities: 15.7924,
              order: 13
            },
            {
              origin: "洛卡山脉",
              level: 4,
              normal: 17.4942,
              glida: 35.7641,
              local: 19.2437,
              fertilizer: 22.0753,
              salve: 24.9044,
              cheese: 24.7794,
              honey: 24.8799,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 14
            },
          ],
        },
        {
          name: "伊尼斯泰尔",
          warArea: true,
          packs: [
            {
              origin: "黎明半岛",
              level: 1,
              normal: 18.9188,
              glida: 46.4905,
              local: 20.8104,
              fertilizer: 21.7564,
              salve: 27.6389,
              cheese: 27.6947,
              honey: 27.8899,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 1
            },
            {
              origin: "咏唱之地",
              level: 1,
              normal: 18.5713,
              glida: 45.757,
              local: 20.4285,
              fertilizer: 21.3569,
              salve: 26.4902,
              cheese: 26.6772,
              honey: 25.2863,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 2
            },
            {
              origin: "莫哈特比",
              level: 2,
              normal: 17.4485,
              glida: 43.1421,
              local: 19.1934,
              fertilizer: 20.0658,
              salve: 24.4989,
              cheese: 24.4496,
              honey: 24.5976,
              bluesalt: 94.8038,
              special: 0,
              antiquities: 0,
              order: 3
            },
            {
              origin: "猎鹰高原",
              level: 2,
              normal: 18.4866,
              glida: 47.7224,
              local: 20.3352,
              fertilizer: 21.2596,
              salve: 27.8340,
              cheese: 27.8340,
              honey: 27.8340,
              bluesalt: 95.1837,
              special: 0,
              antiquities: 0,
              order: 4
            },
            {
              origin: "虎脊山脉",
              level: 2,
              normal: 18.0156,
              glida: 45.3391,
              local: 19.8174,
              fertilizer: 20.7181,
              salve: 24.6721,
              cheese: 24.4743,
              honey: 24.4743,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 5
            },
            {
              origin: "彩虹荒野",
              level: 3,
              normal: 16.7132,
              glida: 42.6544,
              local: 18.3846,
              fertilizer: 19.2203,
              salve: 23.3410,
              cheese: 23.2940,
              honey: 23.3885,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 6
            },
            {
              origin: "烈日峡谷",
              level: 3,
              normal: 18.0626,
              glida: 44.4091,
              local: 21.0017,
              fertilizer: 21.9561,
              salve: 30.2099,
              cheese: 30.3312,
              honey: 30.2709,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 7
            },
            {
              origin: "古代森林",
              level: 3,
              normal: 11.2512,
              glida: 34.1205,
              local: 13.5315,
              fertilizer: 14.1465,
              salve: 20.4440,
              cheese: 20.4029,
              honey: 20.3824,
              bluesalt: 90.8079,
              special: 0,
              antiquities: 0,
              order: 8
            },
            {
              origin: "伊尼斯泰尔",
              level: 3,
              normal: 0,
              glida: 0,
              local: 0,
              fertilizer: 0,
              salve: 0,
              cheese: 0,
              honey: 0,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 9
            },
            {
              origin: "草原之脉",
              level: 4,
              normal: 19.7355,
              glida: 41.5557,
              local: 21.7092,
              fertilizer: 22.6961,
              salve: 30.4672,
              cheese: 30.6521,
              honey: 30.4672,
              bluesalt: 0,
              special: 52.0871,
              antiquities: 0,
              order: 10
            },
            {
              origin: "哈里洛废墟",
              level: 4,
              normal: 19.0588,
              glida: 40.5439,
              local: 20.9651,
              fertilizer: 21.9180,
              salve: 30.2637,
              cheese: 30.0217,
              honey: 30.2637,
              bluesalt: 97.2148,
              special: 47.2641,
              antiquities: 13.8835,
              order: 11
            },
            {
              //current
              origin: "棋盘石林",
              level: 4,
              normal: 15.7586,
              glida: 35.8570,
              local: 18.4453,
              fertilizer: 19.2836,
              salve: 21.9645,
              cheese: 21.9645,
              honey: 22.0972,
              bluesalt: 0,
              special: 24.9282,
              antiquities: 0,
              order: 12
            },
            {
              origin: "翡翠谷",
              level: 4,
              normal: 20.7409,
              glida: 43.3266,
              local: 22.8148,
              fertilizer: 23.8519,
              salve: 36.7299,
              cheese: 36.8043,
              honey: 36.9522,
              bluesalt: 0,
              special: 60.5319,
              antiquities: 15.6797,
              order: 13
            },
            {
              origin: "洛卡山脉",
              level: 4,
              normal: 17.3326,
              glida: 38.2438,
              local: 19.0659,
              fertilizer: 22.0309,
              salve: 28.1724,
              cheese: 28.2289,
              honey: 28.2006,
              bluesalt: 0,
              special: 0,
              antiquities: 0,
              order: 14
            },
          ],
        },
      ],
    },
  ],
}

class AppBootHook {
  constructor(app) {
    this.app = app
  }
  
  async serverDidReady() {
    const ctx = this.app.createAnonymousContext()
    await this.app.model.sync({ force: true })
    const server = await ctx.model.Server.create(
      {
        name: "sea",
        version: "6.5",
        activities: data.activities,
        continents: data.continents,
      },
      {
        include: [
          {
            association: ctx.model.Server.Activity,
            include: [
              {
                association: ctx.model.Activity.Event,
                include: [
                  {
                    association: ctx.model.Event.Time,
                  },
                ],
              },
            ],
          },
          {
            association: ctx.model.Server.Continent,
            include: [
              {
                association: ctx.model.Continent.Area,
                include: [{ association: ctx.model.Area.Pack }],
              },
            ],
          },
        ],
      }
    )
  }
}
module.exports = AppBootHook
